# -*- coding: utf-8 -*-
"""create_gif.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WB8Eg02kKJh4NeAzYTPmc7hFNEIUE4ai
"""

!pip3 install imageio

import imageio.v3 as iio
import os
import matplotlib.pyplot as plt

from google.colab import drive
drive.mount('/content/drive')

data = '/content/drive/MyDrive/Colab_Notebooks/codedex_python/project/data'

# Get a list of all image file names in the directory
filenames = os.listdir(data)
images = []

for filename in filenames:
  # Create complete file paths for multiple files located in the same directory
  full_path = os.path.join(data, filename)
  image_data = iio.imread(full_path)
  images.append(image_data)

# 'team.gif': The name you want to give to your new GIF file.
# 'images'  : The list containing the image data.

# 'duration=500'  : How long each picture should show in the GIF, in milliseconds.
# 'loop=0'        : How many times the GIF should repeat (0 means it keeps looping forever).

iio.imwrite('team.gif', images, duration=500, loop=0)

from IPython.display import Image, display

display(Image(filename='team.gif'))
